// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WMBA_4.Data;

#nullable disable

namespace WMBA_4.Data.WMBAMigrations
{
    [DbContext(typeof(WMBA_4_Context))]
    [Migration("20240417160138_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("WMBA_4.Models.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("WMBA_4.Models.Club", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClubName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("WMBA_4.Models.Division", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClubID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DivisionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ClubID");

                    b.HasIndex("DivisionName")
                        .IsUnique();

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("WMBA_4.Models.Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameTypeID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("GameTypeID");

                    b.HasIndex("LocationID");

                    b.HasIndex("SeasonID");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WMBA_4.Models.GameLineUp", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattingOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.HasIndex("PlayerID");

                    b.HasIndex("TeamID");

                    b.ToTable("GameLineUps");
                });

            modelBuilder.Entity("WMBA_4.Models.GameLineUpPosition", b =>
                {
                    b.Property<int>("GameLineUpID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionID")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameLineUpID", "PositionID");

                    b.HasIndex("PositionID");

                    b.ToTable("GameLineUpPositions");
                });

            modelBuilder.Entity("WMBA_4.Models.GameType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("GameTypes");
                });

            modelBuilder.Entity("WMBA_4.Models.Inning", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InningNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScorePerInning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScorePerInningOpponent")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamGameGameID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamGameTeamID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.HasIndex("TeamID");

                    b.HasIndex("TeamGameTeamID", "TeamGameGameID");

                    b.ToTable("Innings");
                });

            modelBuilder.Entity("WMBA_4.Models.Inplay", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fouls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InningID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NextPlayer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpponentOuts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Outs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerBattingID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerInBase1ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerInBase2ID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerInBase3ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Runs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strikes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamAtBat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Turns")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("InningID");

                    b.HasIndex("PlayerBattingID");

                    b.HasIndex("PlayerInBase1ID");

                    b.HasIndex("PlayerInBase2ID");

                    b.HasIndex("PlayerInBase3ID");

                    b.ToTable("Inplays");
                });

            modelBuilder.Entity("WMBA_4.Models.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("WMBA_4.Models.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("JerseyNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberID")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ranking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeamID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("MemberID")
                        .IsUnique();

                    b.HasIndex("TeamID");

                    b.HasIndex("JerseyNumber", "TeamID")
                        .IsUnique()
                        .HasFilter("[JerseyNumber] is not null and [TeamID] is not null");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("WMBA_4.Models.Position", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("PositionName")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("WMBA_4.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WMBA_4.Models.ScorePlayer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Balls")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BattingOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Doubles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fouls")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameLineUpID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("H")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HBP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Out")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PA")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RBI")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Run")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Singles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrikeOut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Triples")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("GameID");

                    b.HasIndex("GameLineUpID");

                    b.HasIndex("PlayerID");

                    b.ToTable("ScorePlayers");
                });

            modelBuilder.Entity("WMBA_4.Models.Season", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeasonCode")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("SeasonCode")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("WMBA_4.Models.Staff", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("RoleId");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("WMBA_4.Models.StaffDivision", b =>
                {
                    b.Property<int>("DivisionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaffID")
                        .HasColumnType("INTEGER");

                    b.HasKey("DivisionID", "StaffID");

                    b.HasIndex("StaffID");

                    b.ToTable("StaffDivision");
                });

            modelBuilder.Entity("WMBA_4.Models.Team", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DivisionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ranking")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("DivisionID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("WMBA_4.Models.TeamGame", b =>
                {
                    b.Property<int>("TeamID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHomeTeam")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisitorTeam")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("score")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamID", "GameID");

                    b.HasIndex("GameID");

                    b.ToTable("TeamGame");
                });

            modelBuilder.Entity("WMBA_4.Models.TeamStaff", b =>
                {
                    b.Property<int>("TeamID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StaffID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamID", "StaffID");

                    b.HasIndex("StaffID");

                    b.ToTable("TeamStaff");
                });

            modelBuilder.Entity("WMBA_4.ViewModels.GameEndSeasonVM", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DivisionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TeamHome")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamVisitor")
                        .HasColumnType("TEXT");

                    b.Property<int>("scoreHome")
                        .HasColumnType("INTEGER");

                    b.Property<int>("scoreVisitor")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable((string)null);

                    b.ToView("GamesEndSeason", (string)null);
                });

            modelBuilder.Entity("WMBA_4.ViewModels.PlayerEndSeasonVM", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClubName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DivisionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Season")
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable((string)null);

                    b.ToView("PlayersEndSeason", (string)null);
                });

            modelBuilder.Entity("WMBA_4.ViewModels.PlayerStatsVM", b =>
                {
                    b.Property<int>("AB")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AVG")
                        .HasColumnType("REAL");

                    b.Property<int>("BB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Doubles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("G")
                        .HasColumnType("INTEGER");

                    b.Property<int>("H")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HBP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JerseyNumber")
                        .HasColumnType("TEXT");

                    b.Property<double>("OBP")
                        .HasColumnType("REAL");

                    b.Property<double>("OPS")
                        .HasColumnType("REAL");

                    b.Property<int>("Out")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PA")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Player")
                        .HasColumnType("TEXT");

                    b.Property<int>("RBI")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Run")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SLG")
                        .HasColumnType("REAL");

                    b.Property<int>("SO")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Singles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.Property<int>("Triples")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToView("PlayerStats", (string)null);
                });

            modelBuilder.Entity("WMBA_4.ViewModels.TeamStatsVM", b =>
                {
                    b.Property<int>("AB")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AVG")
                        .HasColumnType("REAL");

                    b.Property<int>("BB")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DivisionName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Doubles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("G")
                        .HasColumnType("INTEGER");

                    b.Property<int>("H")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HBP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("OBP")
                        .HasColumnType("REAL");

                    b.Property<double>("OPS")
                        .HasColumnType("REAL");

                    b.Property<int>("Out")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PA")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RBI")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Run")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SLG")
                        .HasColumnType("REAL");

                    b.Property<int>("SO")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Singles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .HasColumnType("TEXT");

                    b.Property<int>("Triples")
                        .HasColumnType("INTEGER");

                    b.ToTable((string)null);

                    b.ToView("TeamStats", (string)null);
                });

            modelBuilder.Entity("WMBA_4.Models.Club", b =>
                {
                    b.HasOne("WMBA_4.Models.City", "City")
                        .WithMany("Clubs")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WMBA_4.Models.Division", b =>
                {
                    b.HasOne("WMBA_4.Models.Club", "Club")
                        .WithMany("Divisions")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("WMBA_4.Models.Game", b =>
                {
                    b.HasOne("WMBA_4.Models.GameType", "GameType")
                        .WithMany("Games")
                        .HasForeignKey("GameTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WMBA_4.Models.Location", "Location")
                        .WithMany("Games")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WMBA_4.Models.Season", "Season")
                        .WithMany("Games")
                        .HasForeignKey("SeasonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameType");

                    b.Navigation("Location");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("WMBA_4.Models.GameLineUp", b =>
                {
                    b.HasOne("WMBA_4.Models.Game", "Game")
                        .WithMany("GameLineUps")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMBA_4.Models.Player", "Player")
                        .WithMany("GameLineUps")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMBA_4.Models.Team", "Team")
                        .WithMany("GameLineUps")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WMBA_4.Models.GameLineUpPosition", b =>
                {
                    b.HasOne("WMBA_4.Models.GameLineUp", "GameLineUp")
                        .WithMany("GameLineUpPositions")
                        .HasForeignKey("GameLineUpID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMBA_4.Models.Position", "Position")
                        .WithMany("GameLineUpPositions")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameLineUp");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("WMBA_4.Models.Inning", b =>
                {
                    b.HasOne("WMBA_4.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMBA_4.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMBA_4.Models.TeamGame", null)
                        .WithMany("Innings")
                        .HasForeignKey("TeamGameTeamID", "TeamGameGameID");

                    b.Navigation("Game");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WMBA_4.Models.Inplay", b =>
                {
                    b.HasOne("WMBA_4.Models.Inning", "Inning")
                        .WithMany("Inplays")
                        .HasForeignKey("InningID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMBA_4.Models.Player", "PlayerBatting")
                        .WithMany("PlayerBatting")
                        .HasForeignKey("PlayerBattingID");

                    b.HasOne("WMBA_4.Models.Player", "PlayerInBase1")
                        .WithMany("PlayerBase1")
                        .HasForeignKey("PlayerInBase1ID");

                    b.HasOne("WMBA_4.Models.Player", "PlayerInBase2")
                        .WithMany("PlayerBase2")
                        .HasForeignKey("PlayerInBase2ID");

                    b.HasOne("WMBA_4.Models.Player", "PlayerInBase3")
                        .WithMany("PlayerBase3")
                        .HasForeignKey("PlayerInBase3ID");

                    b.Navigation("Inning");

                    b.Navigation("PlayerBatting");

                    b.Navigation("PlayerInBase1");

                    b.Navigation("PlayerInBase2");

                    b.Navigation("PlayerInBase3");
                });

            modelBuilder.Entity("WMBA_4.Models.Location", b =>
                {
                    b.HasOne("WMBA_4.Models.City", "City")
                        .WithMany("Locations")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("WMBA_4.Models.Player", b =>
                {
                    b.HasOne("WMBA_4.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WMBA_4.Models.ScorePlayer", b =>
                {
                    b.HasOne("WMBA_4.Models.Game", null)
                        .WithMany("ScorePlayers")
                        .HasForeignKey("GameID");

                    b.HasOne("WMBA_4.Models.GameLineUp", "GameLineUp")
                        .WithMany("ScoresPlayer")
                        .HasForeignKey("GameLineUpID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMBA_4.Models.Player", null)
                        .WithMany("ScorePlayers")
                        .HasForeignKey("PlayerID");

                    b.Navigation("GameLineUp");
                });

            modelBuilder.Entity("WMBA_4.Models.Staff", b =>
                {
                    b.HasOne("WMBA_4.Models.Role", "Roles")
                        .WithMany("StaffMembers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("WMBA_4.Models.StaffDivision", b =>
                {
                    b.HasOne("WMBA_4.Models.Division", "Division")
                        .WithMany("StaffDivision")
                        .HasForeignKey("DivisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMBA_4.Models.Staff", "Staff")
                        .WithMany("StaffDivision")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("WMBA_4.Models.Team", b =>
                {
                    b.HasOne("WMBA_4.Models.Division", "Division")
                        .WithMany("Teams")
                        .HasForeignKey("DivisionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("WMBA_4.Models.TeamGame", b =>
                {
                    b.HasOne("WMBA_4.Models.Game", "Game")
                        .WithMany("TeamGames")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WMBA_4.Models.Team", "Team")
                        .WithMany("TeamGames")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WMBA_4.Models.TeamStaff", b =>
                {
                    b.HasOne("WMBA_4.Models.Staff", "Staff")
                        .WithMany("TeamStaff")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WMBA_4.Models.Team", "Team")
                        .WithMany("TeamStaff")
                        .HasForeignKey("TeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("WMBA_4.Models.City", b =>
                {
                    b.Navigation("Clubs");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("WMBA_4.Models.Club", b =>
                {
                    b.Navigation("Divisions");
                });

            modelBuilder.Entity("WMBA_4.Models.Division", b =>
                {
                    b.Navigation("StaffDivision");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("WMBA_4.Models.Game", b =>
                {
                    b.Navigation("GameLineUps");

                    b.Navigation("ScorePlayers");

                    b.Navigation("TeamGames");
                });

            modelBuilder.Entity("WMBA_4.Models.GameLineUp", b =>
                {
                    b.Navigation("GameLineUpPositions");

                    b.Navigation("ScoresPlayer");
                });

            modelBuilder.Entity("WMBA_4.Models.GameType", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("WMBA_4.Models.Inning", b =>
                {
                    b.Navigation("Inplays");
                });

            modelBuilder.Entity("WMBA_4.Models.Location", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("WMBA_4.Models.Player", b =>
                {
                    b.Navigation("GameLineUps");

                    b.Navigation("PlayerBase1");

                    b.Navigation("PlayerBase2");

                    b.Navigation("PlayerBase3");

                    b.Navigation("PlayerBatting");

                    b.Navigation("ScorePlayers");
                });

            modelBuilder.Entity("WMBA_4.Models.Position", b =>
                {
                    b.Navigation("GameLineUpPositions");
                });

            modelBuilder.Entity("WMBA_4.Models.Role", b =>
                {
                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("WMBA_4.Models.Season", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("WMBA_4.Models.Staff", b =>
                {
                    b.Navigation("StaffDivision");

                    b.Navigation("TeamStaff");
                });

            modelBuilder.Entity("WMBA_4.Models.Team", b =>
                {
                    b.Navigation("GameLineUps");

                    b.Navigation("Players");

                    b.Navigation("TeamGames");

                    b.Navigation("TeamStaff");
                });

            modelBuilder.Entity("WMBA_4.Models.TeamGame", b =>
                {
                    b.Navigation("Innings");
                });
#pragma warning restore 612, 618
        }
    }
}
